[theme_header]
    name = "Apprentice"
    version = "-"
    author = "Jeet Sukumaran"
    description = "Apprentice is a dark, low-contrast colorscheme for Vim based on the awesome Sorcerer by Jeet Sukumaran."

[file_manager]
    back = [38, 38, 38]
    select = [188, 188, 188]
    folder = [95, 175, 175]
    folder_select = [95, 135, 135]
    file = [255, 255, 255]
    file_select = [108, 108, 108]